version: '3.8'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  elasticsearch:
    image: elasticsearch:8.2.2
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic

  kibana:
    image: kibana:8.2.2
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

  rest-mongo:
    image: rest-mongo:latest
    container_name: rest-mongo
    build:
      context: rest-mongo
      dockerfile: Dockerfile
    depends_on:
      - rest-elasticsearch
    links:
      - mongodb
    environment:
      - JAVA_OPTS=-Dspring.data.mongodb.host=mongodb
    ports:
      - "8090:8090"
      - "5001:5001"
    restart: unless-stopped

  rest-elasticsearch:
    image: rest-elasticsearch:latest
    container_name: rest-elasticsearch
    build:
      context: rest-elasticsearch
      dockerfile: Dockerfile
    links:
      - elasticsearch
    ports:
      - "8091:8091"
      - "5002:5002"
    restart: unless-stopped

volumes:
  data: {}
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
